name: knic
favicon: null
layout_spectrum: 0.1615536231547594
typography_spectrum: 0.0014405394904315472
title: knic pfost
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1f1f1f'
    - '#ff876c'
    - '#716e67'
    - '#eac4b7'
  brandStrength: 0.3125
  lightness: 0.3125
  saturation: 0.4375
  rhythmicContrast: 1
purpose: []
