name: knic
favicon: null
layout_spectrum: 0.1615536231547594
typography_spectrum: 0.0014405394904315472
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.25450068316422403
  lightness: 0.22461133170872927
  saturation: 0.35806662566028535
  rhythmicContrast: 0.943149103783071
purpose: []
